### ISSUE TITLE
اضافه کردن سطر چهارم و  پنجم خرید و فروش

### ISSUE THREAD

**Issue by TayebAlipour** [miladj/PyTse#12]
سلام وقت بخیر
با تشکر از کد خوبتون
با توجه به تغییر سایت سازمان بورس و اضافه شدن سطر چهارم و پنجم صف های خرید و فروش، چطوری این اطلاعات را به کد شما اضافه کنیم؟

متشکرم

**Comment by kohestanimahdi** [comment]
سلام و وقت بخیر
نیازی به تغییر چیزی نیست. تنها اعداد اخر فیلدهای مورد نظر خود را با 4 و 5 استفاده کنید.
به عنوان مثال برای : 
حجم فروش- سطر پنجم : qo5
