### ISSUE TITLE
run this project in pycharm

### ISSUE THREAD

**Issue by hshahsavan** [miladj/PyTse#13]
سلام یه سوال داشتم من  این پروژه رو از گیت هاب در قسمت کلون در پای چارم آوردم و فایل پایتون تست  رو  اجرا میکنم هیچی نشون نمیده 
from pytse.pytse import PyTse, SymbolData
from unittest.mock import patch
from pathlib import Path
from nose.tools import assert_equal, assert_is_not_none, assert_is_instance

def test_server_response():
    with patch('pytse.pytse.PyTse._PyTse__get_data_from_server') as mock_get:
        mock_get.return_value = Path("tests/sampledata.txt").read_text()

        pytse = PyTse()
        symbols = pytse.symbols_data
        symbol = symbols["IRO1NIKI0001"]
        print(symbol)
        assert_is_not_none(symbol)
        assert_is_instance(symbol, SymbolData)
        assert_equal(symbol.tvol, 8566607)
        assert_equal(symbol.pmax, 11396)
        assert_equal(symbol.pmin, 10570)
        assert False

**Comment by miladj** [comment]
باید یه فایل پایتون برای اجرا خودتون بسازید
و این کد رو توش بزارید
from pytse.pytse import PyTse,SymbolData


if(__name__=="__main__"):
    PyTse.request_timeout = 20#changing timeout default=30 !apply to all requests
    pytse=PyTse()#read_symbol_data=True,read_client_type=False
    pytse.read_client_type() # در صورت نیاز به اطلاعات حقیقی
    symbols=pytse.symbols_data
    symbol=symbols["IRO1MKBT0001"]
    symbol.fill_data() #درصورت نیاز به اطلاعات "میانگین حجم ماه "و "سهام شناور" فرخوانی شود
    symbol_history_data=symbol.get_symbol_history()
    print(symbol_history_data["20210106"])
    print(symbol)
    print(symbol.pl)
    print(symbol.ct.Buy_CountI) #fill_data()
    print(symbol["ct"]["Buy_CountI"]) #fill_data()

**Comment by miladj** [comment]
فایل 
main.py
رو اجرا کنید
