### ISSUE TITLE
جستجو براساس نام نماد

### ISSUE THREAD

**Issue by hshahsavan** [miladj/PyTse#15]
سلام 
باتشکر از برنامه بسیار خوبی که نوشتید 
آیا امکان این هست که اطلاعات یک نماد را با استفاده از نام نماد استخراج کنیم بجای داشتن کد معاملاتی نماد 
به عنوان مثال بجای استفاده از symbol=symbols["IRO1SIPA0001"] نام نماد را جایگذاری کنیم

**Comment by miladj** [comment]
سلام
از نسخه 1.6.2
استفاده کنید داره این قابلیت رو 
`pytse.symbols_data_by_symbol["خساپا"]`

**Comment by hshahsavan** [comment]
سلام نسخه جدید ارور می دهد [key error]
در بعضی از نمادها مثل خساپا
