### ISSUE TITLE
دریافت اطلاعات تابلو

### ISSUE THREAD

**Issue by tagrobi2** [miladj/PyTse#16]
با عرض سلام
ببخشید لینکی نیست که بتونم اطلاعات تابلوی (تعداد خریدار سطور مختلف و قیمت های سطور اول تا پنجم) همه ی نمادها را یکجا دریافت کنم؟

**Comment by miladj** [comment]
سلام
از طریق فیلدهای
pd1,zd1 ,......
میتونید دسترسی داشته باشید
