### ISSUE TITLE
نبودن بعضی از نمادها

### ISSUE THREAD

**Issue by mostafa2msh** [miladj/PyTse#17]
سلام. اطلاعات برخی نمادها مثل وغدیر  رو نمیده با تشکر
print(pytse.symbols_data_by_symbol["وغدیر"])

**Comment by miladj** [comment]
سلام
نمادهایی که متوقف باشند تو لیست نیست
اما در مورد وغدیر فکر میکنم مشکل حرف ی باشه
وغدیر رواز تو سایت کپی کنید
`pytse.symbols_data["IRO1GDIR0001"]`
با این هم تست کنید

**Comment by mostafa2msh** [comment]
با تشکر وغدیر مشکلش حل شد. برای نمادهای بسته راهی نیست که داخل لیست بیاد؟

**Comment by mostafa2msh** [comment]
لطفا راهنمایی کنید

**Comment by miladj** [comment]
سلام
اطلاعات از صفحه دیده بان خونده میشه 
تو اون صفحه نمادهای بسته وجود ندارن
