### ISSUE TITLE
اطلاعات کامل نماد

### ISSUE THREAD

**Issue by hashemiy66** [miladj/PyTse#3]
با سلام...ببخشید امکان داشتن اطلاعات کامل نماد از روز اولیه ی عرضه وجود نداره؟
خود سایت Tsetmc  این اطلاعات رو بصورت فایل Excel در اختیار قرار میده...
چطوری امکان استخراج قیمت ها وجود داره؟

**Comment by h4mid007** [comment]
سلام
برای دسترسی به قیمت های سهم از روز عرضه‌ی اولیه بصورت فایل سی اس وی، ابتدا باید کد نماد مورد نظر (inscode) رو داشته باشید:

> {
> "inscode": "**45392752356003555**",
> "iid": "IRO3STIZ0001",
> ...
> }

و بعد آدرس زیر:

> www.tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=45392752356003555

**Comment by miladj** [comment]
> 
> 
> سلام
> برای دسترسی به قیمت های سهم از روز عرضه‌ی اولیه بصورت فایل سی اس وی، ابتدا باید کد نماد مورد نظر (inscode) رو داشته باشید:
> 
> > {
> > "inscode": "**45392752356003555**",
> > "iid": "IRO3STIZ0001",
> > ...
> > }
> 
> و بعد آدرس زیر:
> 
> > [www.tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=45392752356003555](http://www.tsetmc.com/tsev2/data/Export-txt.aspx?t=i&a=1&b=0&i=45392752356003555)

به نظرتون اینو میشه به api اضافه کرد؟

**Comment by h4mid007** [comment]
> 
> به نظرتون اینو میشه به api اضافه کرد؟
> 
آره میشه واسه آبجکت هر نماد، یه فانکشن تعریف کنیم که در صورت درخواست کاربر، سابقه ی قیمتی واسه اون نماد رو بگیره و بعد دیتا رو parse میکنیم و ...(مثل فانکشن fill_data() که شناور و میانگین حجم رو میگرفت)

**Comment by AdeptWanderer** [comment]
سلام دوستان گاهی تعداد رکورد های نماد ها کم و زیاد میشه یا حتی رکورد های خالی بر میگرده؟ به عنوان مثال گاهی 1134 نماد پیدا میکنه گاهی 1060 تا. دلیلش رو شما می دونید؟

**Comment by miladj** [comment]
> 
> 
> با سلام...ببخشید امکان داشتن اطلاعات کامل نماد از روز اولیه ی عرضه وجود نداره؟
> خود سایت Tsetmc این اطلاعات رو بصورت فایل Excel در اختیار قرار میده...
> چطوری امکان استخراج قیمت ها وجود داره؟



> 
> 
> > به نظرتون اینو میشه به api اضافه کرد؟
> 
> آره میشه واسه آبجکت هر نماد، یه فانکشن تعریف کنیم که در صورت درخواست کاربر، سابقه ی قیمتی واسه اون نماد رو بگیره و بعد دیتا رو parse میکنیم و ...(مثل فانکشن fill_data() که شناور و میانگین حجم رو میگرفت)

get_symbol_history
اضافه شد

**Comment by mostafa2msh** [comment]
میشه برا طریقه استفاده get_symbol_history یه مثال بزنید
