### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by ebrahimi1989** [miladj/PyTse#4]
ارر در زمانی که نماد مورد نظر ممنوع-متوقف باشد

**Comment by h4mid007** [comment]
بیشتر توضیح بدین، مثلا کدوم نماد؟

**Comment by ebrahimi1989** [comment]
لیستی از نمادهارو که به عنوان ورودی بهش میدم روی بعضی از نمادها ارر میده. اون نمادهارو توی سایت تی اس ای سرچ کردم دیدم که اون نمادها ممنوع-متوقف هستش
شما الان میتونی با همین نمونه کدی که گذاشتی نماد خمحرکه رو تست کنی همین ارر رو بهت میده

**Comment by h4mid007** [comment]
آره خب، این پکیج اطلاعات رو از بخش **[دیده بان بازار](http://www.tsetmc.com/Loader.aspx?ParTree=15131F)** میگیره و هر نمادی که توی دیده بان بازار نباشه، اینجا نشون نمیده.

**Comment by ebrahimi1989** [comment]
چه شرطی میشه گذاشت که وقتی نیست ارر نده؟

**Comment by h4mid007** [comment]
نمیدونم کدتون چطوره، ولی میتونید از try و except استفاده کنید:
```
try:
    code
except:
    pass
```

**Comment by ebrahimi1989** [comment]
ممنون

**Comment by miladj** [comment]
البته اینجوری هم میتونید چک کنید ببینید نماد هست یا نه
```
    symbolIsin = "IRO1MKBT0001"
    if symbolIsin in symbols:
        symbol = symbols[symbolIsin ]
        print(symbol)
```
