### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by ebrahimi1989** [miladj/PyTse#5]
در بعضی مواقع این ارر رو نشون میده ولی خیلی وقتا نشون نمیده !
'SymbolData' object has no attribute 'ct'

**Comment by h4mid007** [comment]
بعضی  از نمادهای اختیار خرید و فروش، تسهیلات و ... اطلاعات خرید و فروش حقوقی ندارن (فکر کنم چون توی اون روز معامله ای صورت نگرفته)
مثل:

http://www.tsetmc.com/Loader.aspx?ParTree=151311&i=143187001116603

http://www.tsetmc.com/loader.aspx?ParTree=151311&i=72044554577552304

که ارور میده. بستگی داره خودتون چطور این ارور رو دور بزنین مثلا try و except

**Comment by ebrahimi1989** [comment]
در تاریخ 29 خرداد برای نمادهایی مثه کگل و چفیبر هم این ارر رو نشون میده در صورتی که تو این نمادها اطلاعات حقیقی و حقوقی دارن و خرید و فروش هم انجام شده

**Comment by h4mid007** [comment]
هنوز مشکل پابرجاست؟ من همین الان برای غگل و چفیبر امتحان کردم مشکلی نداشت.

![Screenshot_20200618-154406171](https://user-images.githubusercontent.com/53395419/85013880-d78e0700-b154-11ea-9592-1dddd1330f75.jpg)

**Comment by ebrahimi1989** [comment]
نه درست شد 
ممنون
