### ISSUE TITLE
نمونه کد

### ISSUE THREAD

**Issue by abolfalk** [miladj/PyTse#6]
میشه یه نمونه کد برای استفاده از این پکیج بزارین من هرچی دارم سعی می کنم نمی تونم ازش سر در بیارم

**Comment by h4mid007** [comment]
سلام
این کد بعنوان نمونه :

```
from pytse.pytse import PyTse,SymbolData


if(__name__=="__main__"):
    pytse=PyTse()#read_symbol_data=True,read_client_type=False
    pytse.read_client_type() # در صورت نیاز به اطلاعات حقیقی
    symbols=pytse.symbols_data
    symbol=symbols["IRO1MKBT0001"] 
    symbol.fill_data() #درصورت نیاز به اطلاعات "میانگین حجم ماه "و "سهام شناور" فرخوانی شود
    print(symbol)
```

دقیقا چه کاربردی مد نظرت هست تا راهنماییت کنم

**Comment by abolfalk** [comment]
میخوام یه لیست بهش بدم تا برای تک تک نماد های اون لیست برام نسبت خریدار فروشنده حساب کنه
((تعداد فروش حقیقی)/(حجم فروش حقیقی)) / ((تعداد خرید حقیقی)/(حجم خرید حقیقی))
برای هر سهم

**Comment by mousaviaaa** [comment]
> سلام
> این کد بعنوان نمونه :
> 
> ```
> from pytse.pytse import PyTse,SymbolData
> 
> 
> if(__name__=="__main__"):
>     pytse=PyTse()#read_symbol_data=True,read_client_type=False
>     pytse.read_client_type() # در صورت نیاز به اطلاعات حقیقی
>     symbols=pytse.symbols_data
>     symbol=symbols["IRO1MKBT0001"] 
>     symbol.fill_data() #درصورت نیاز به اطلاعات "میانگین حجم ماه "و "سهام شناور" فرخوانی شود
>     print(symbol)
> ```
> 
> دقیقا چه کاربردی مد نظرت هست تا راهنماییت کنم
سلام
من میخوام به اطلاعات حقیقی ها دسترسی پیدا کنم ولی نمیتونم
 print(symbol["ct:Buy_CountI"])
اینو مینویسم قبلشم فراخوانی کردم ولی نمیاره

**Comment by miladj** [comment]
> print(symbol["ct:Buy_CountI"])
اینجوری اطلاعات رو بگیرید
        print(symbol.ct.Buy_CountI)
        print(symbol["ct"]["Buy_CountI"])
