### ISSUE TITLE
اشکال در فایل exe

### ISSUE THREAD

**Issue by AfcEagle** [miladj/PyTse#9]
با سلام دوست عزیز و تشکر بابت لطفی که  کردید
برای دریافت اطلاعات حقیقی و حقوقی یه کد نوشتم که وقتی از خود پایتون اجرا میکنم عالی کار میکنه
ولی وقتی با pyinstaller اجرا میکنم مشکل دارم و پوشه نرمافزار رو پیدا نمیکنه و به فایل symbols_name.json دسترسی نداره و ..  (("pytse_client/data/symbols_name.json/..."))
پوشه ای که تو temp برای برنامه ساخته میشه اصلا پوشه pytse_client وزیر شاخه هاشو نداره

با این کد ها خواستم پوشه پیشفرض رو تغییر بدم ولی نشد. ظاهرا تغییر میده ولی بار وقتی لازم میشه که چیزی بخونه میره باز از پوشه پیشفرض (که وجود نداره) بخونه
```
            tse.config.pytse_dir = cur_path
            tse.symbols_data.config.DATA_BASE_PATH = cur_path


موندم چیکار کنم :(

**Comment by miladj** [comment]
سلام
یه مقدار بیشتر توضیح بدید
اگه یه سمپل هم بدید بهتره
